spring:
  application:
    name: trading-engine-backend
  datasource:
    url: jdbc:postgresql://localhost:5432/trading_engine?options=-c%20timezone=UTC
    username: myuser
    password: mypassword
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  data:
    redis:
      host: localhost
      port: 6379
